name: 🐞 버그 리포트
description: 동작 중 발견한 버그를 신고합니다.
title: "[Bug] "
labels: [bug]
body:
  - type: textarea
    id: description
    attributes:
      label: 버그 설명
      description: 문제가 발생한 상황을 명확하게 설명해주세요.
      placeholder: 예: 로그인 버튼을 눌러도 반응이 없습니다.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: 재현 방법
      description: 버그를 재현할 수 있는 단계들을 작성해주세요.
      placeholder: |
        1. 앱 실행
        2. 로그인 화면으로 이동
        3. 로그인 버튼 클릭
    validations:
      required: true

  - type: input
    id: expected
    attributes:
      label: 기대 동작
      description: 어떤 결과가 나와야 정상인가요?
      placeholder: 로그인 화면에서 메인 화면으로 이동

  - type: input
    id: environment
    attributes:
      label: 실행 환경
      description: 실행된 환경을 알려주세요.
      placeholder: OS, 브라우저, Unity 버전 등

  - type: textarea
    id: screenshot
    attributes:
      label: 스크린샷
      description: 가능하다면 문제를 보여주는 스크린샷이나 로그를 첨부해주세요.
